name: hera_stats
channels:
  - conda-forge
  - defaults
dependencies:
  - aipy>=3.0.0rc2
  - astropy>=2.0
  - h5py
  - matplotlib>=2.0
  - nose
  - numpy>=1.19
  - pip
  - pyyaml
  - scikit-learn
  - scipy>=1.2.0
  - jupyter
  - six
  - coveralls
  - pyuvdata
  - pip:
    - git+https://github.com/HERA-Team/linsolve
    - git+https://github.com/HERA-Team/uvtools
    - git+https://github.com/HERA-Team/hera_cal
    - git+https://github.com/HERA-Team/hera_pspec
    - pyephem
    - multiprocess
    - more_itertools
